name: Cypress Tests

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-24.04
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Approve build scripts
        run: pnpm approve-builds

      - name: Generate cache key
        id: cache-key
        run: echo "value=${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: pnpm run build
          install-command: pnpm install

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: dist

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ steps.cache-key.outputs.value }}

  cypress-run:
    runs-on: ubuntu-24.04
    needs: install
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore Cypress cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: cypress-${{ needs.install.outputs.cache-key }}

      - name: Install dependencies
        run: pnpm install

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run preview
          browser: chrome
          install-command: pnpm install
