name: git-act-react-testing-library

# Specifies the trigger for this workflow.
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onpushpull_requestpull_request_targetpathspaths-ignore
on: [pull_request]

# Groups together all the jobs that run in the workflow.
jobs:
  jb-test-rtl:
    # This means that the job will execute on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
