name: git-act-react-testing-library

# Specifies the trigger for this workflow.
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onpushpull_requestpull_request_targetpathspaths-ignore
on: [pull_request]

# Groups together all the jobs that run in the workflow.
jobs:
  jb-test-rtl:
    # This means that the job will execute on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
