name: Cypress Tests

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  cypress-run:
    runs-on: ubuntu-24.04
    needs: install

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
